#!/bin/bash
# "THE BEER-WARE LICENSE" (Revision 42):
# Kamil "elwin013" Banach wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.
if [ "$1" = "--proclaim-superiority" ]; then BEST="Arch Linux is the best!"; fi;
CPU_INFO=`cat /proc/cpuinfo | grep 'model name' | cut -f 2 -d ':' | sed -n '1p' | sed 's/CPU //;'`;
CPU_INFO_LENGTH=${#CPU_INFO};
COLUMNS=`tput cols`;
if [ $(($CPU_INFO_LENGTH+40)) -gt $(($COLUMNS)) ]; then               # So, it's really bad code... But it works!
  CPU_INFO_MORE=${CPU_INFO: $(($COLUMNS-$CPU_INFO_LENGTH-40))};       # Cut part from end
  CPU_INFO=${CPU_INFO:0:$((${CPU_INFO_LENGTH}-${#CPU_INFO_MORE}))};   # Remove that part
  CPU_INFO_MORE=${CPU_INFO##* }$CPU_INFO_MORE;                        # Cut from last space to end and join with second line
  CPU_INFO=${CPU_INFO%${CPU_INFO##* }};                               # Remove that part
fi;

echo -e "[?1034h                   [38;5;32m1[0;0;0m
                  [38;5;32m001[0;0;0m
                 [38;5;32m11000[0;0;0m
                 [38;5;32m100111[0;0;0m
                [38;5;32m00111001[0;0;0m             [38;5;32mOS: [0;0;0mArch Linux "`uname -m`"
                 [38;5;32m10111001[0;0;0m            [38;5;32mHostname: [0;0;0m"`uname -n`"
              [38;5;32m010101100100[0;0;0m           [38;5;32mKernel: [0;0;0m"`uname -r`"
            [38;5;32m001100100011111[0;0;0m          [38;5;32mUptime: [0;0;0m"`uptime | awk '{print $3}' | sed 's/,//;'`"
           [38;5;32m00011011010001001[0;0;0m         [38;5;32mShell: [0;0;0m${SHELL#/*/*}
          [38;5;32m1110000100110011101[0;0;0m        [38;5;32mRAM: [0;0;0m"`free -m | sed -n '2p' | awk '{print $3"M / "$2"M"}'`"
         [38;5;32m100010111[0;0;0m    [38;5;32m01100001[0;0;0m       [38;5;32mCPU:[0;0;0m${CPU_INFO}
        [38;5;32m10010101[0;0;0m       [38;5;32m01111110[0;0;0m           ${CPU_INFO_MORE}
       [38;5;32m100110001[0;0;0m        [38;5;32m10011[0;0;0m
      [38;5;32m1010111110[0;0;0m        [38;5;32m110110010[0;0;0m    $BEST
    [38;5;32m111100010[0;0;0m             [38;5;32m111111101[0;0;0m
   [38;5;32m01111[0;0;0m                        [38;5;32m1100[0;0;0m
  [38;5;32m11[0;0;0m                                [38;5;32m1[0;0;0m"
